import os
import sys
import unittest
import asyncio
from pathlib import Path

# Resolve project root dynamically for imports
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
sys.path.append(PROJECT_ROOT)

from sqlalchemy.future import select
from qdrant_client.models import Filter, FieldCondition, MatchValue

from config.settings import settings
from src.core.database import async_session_maker, engine
from src.models.relational import Base, Document, Chunk
from src.core.vector import qdrant_client
from src.core.graph import neo4j_driver
from src.workers.tasks import async_ingestion_pipeline

class TestIngestionPipelineE2E(unittest.IsolatedAsyncioTestCase):
    """
    End-to-End integration test for the document ingestion pipeline.
    Requires active connections to PostgreSQL, Qdrant, and Neo4j, as well as valid API keys.
    """

    async def asyncSetUp(self):
        # Locate the sample PDF we used in previous extraction tests
        self.test_filename = "sample-1-4.pdf"
        self.test_file_path = os.path.join(PROJECT_ROOT, "data", "raw", self.test_filename)
        
        if not os.path.exists(self.test_file_path):
            self.skipTest(f"Integration test requires a sample document at {self.test_file_path}")

        # Initialize the relational schema if it does not exist in PostgreSQL.
        # Note: In production, this should be handled via Alembic migrations.
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.drop_all)
            await conn.run_sync(Base.metadata.create_all)

        # Ensure a clean slate before testing to prevent false positives from prior runs
        # await self._teardown_test_data()

    async def test_full_ingestion_lifecycle(self):
        """Executes the pipeline and validates data propagation across all three storage layers."""
        
        # 1. Execute Pipeline
        print(f"\n[*] Executing pipeline for {self.test_filename}...")
        result_message = await async_ingestion_pipeline(self.test_file_path)
        self.assertIn("Successfully processed", result_message)

        # 2. Validate PostgreSQL (The Source of Truth)
        print("[*] Validating PostgreSQL persistence...")
        async with async_session_maker() as session:
            doc_query = select(Document).where(Document.filename == self.test_filename)
            doc_result = await session.execute(doc_query)
            db_document = doc_result.scalar_one_or_none()
            
            self.assertIsNotNone(db_document, "Document record was not created in PostgreSQL.")
            
            chunk_query = select(Chunk).where(Chunk.document_id == db_document.id)
            chunk_result = await session.execute(chunk_query)
            db_chunks = chunk_result.scalars().all()
            
            self.assertGreater(len(db_chunks), 0, "No chunks were persisted to PostgreSQL.")
            
            # Extract the UUIDs generated by SQLAlchemy
            chunk_ids = [chunk.id for chunk in db_chunks]

        # 3. Validate Qdrant (The Pointer Strategy)
        print("[*] Validating Qdrant indexing and pointer strategy...")
        retrieved_points = await qdrant_client.retrieve(
            collection_name=settings.QDRANT_COLLECTION_NAME,
            ids=chunk_ids
        )
        
        self.assertEqual(
            len(retrieved_points), 
            len(chunk_ids), 
            "Mismatch between PostgreSQL chunk count and Qdrant vector count."
        )

        for point in retrieved_points:
            payload = point.payload
            # Verify structural metadata exists
            self.assertIn("filename", payload)
            self.assertEqual(payload["filename"], self.test_filename)
            
            # CRITICAL ARCHITECTURAL ASSERTION: Ensure raw text is NOT in Qdrant
            self.assertNotIn(
                "text", 
                payload, 
                "Pointer strategy failed: Raw text is bleeding into the Qdrant payload."
            )

        # 4. Validate Neo4j (Graph Provenance)
        print("[*] Validating Neo4j entity extraction and provenance linking...")
        async with neo4j_driver.session() as session:
            query = """
            MATCH (d:Document {name: $filename})<-[m:MENTIONED_IN]-(e)
            RETURN count(e) as entity_count
            """
            result = await session.run(query, filename=self.test_filename)
            record = await result.single()
            entity_count = record["entity_count"]

            self.assertGreater(
                entity_count, 
                0, 
                "No entities were extracted and linked to the document in Neo4j."
            )

    async def _teardown_test_data(self):
        """Purges test artifacts from all databases to maintain a pristine environment."""
        
        # Purge PostgreSQL
        async with async_session_maker() as session:
            query = select(Document).where(Document.filename == self.test_filename)
            result = await session.execute(query)
            db_document = result.scalar_one_or_none()
            if db_document:
                await session.delete(db_document)
                await session.commit()

        # Purge Qdrant
        await qdrant_client.delete(
            collection_name=settings.QDRANT_COLLECTION_NAME,
            points_selector=Filter(
                must=[
                    FieldCondition(
                        key="filename", 
                        match=MatchValue(value=self.test_filename)
                    )
                ]
            )
        )

        # Purge Neo4j (Detach delete the document node; we leave the entities intact 
        # as they might be valid canonical nodes shared by other documents)
        async with neo4j_driver.session() as session:
            query = "MATCH (d:Document {name: $filename}) DETACH DELETE d"
            await session.run(query, filename=self.test_filename)

    async def asyncTearDown(self):
        await self._teardown_test_data()

if __name__ == "__main__":
    unittest.main()